hybris-patches: Rebase on top of Sony's changes 20220125
mer-hybris/hybris-patches pull request #23
Opened 2022-02-03 11:49 UTC by sledges

2022-02-03 11:51 UTC, Thaodan approved these changes

2022-02-03 12:12 UTC, Thaodan requested changes
Please drop the patch, see:
https://github.com/sonyxperiadev/kernel-sony-msm-4.19-common/commit/985492a4e0115e620a4c1befb4245c53fb340503

2022-02-04 12:19 UTC, sledges commented
Dropped. This merge will need to be added to dhd together with new manifest https://github.com/mer-hybris/android/pull/151

2022-02-04 12:23 UTC, Thaodan approved these changes

2022-02-04 12:28 UTC, merged