Allow input group to use vibrator.
mer-hybris/hybris-patches pull request #5
Opened 2020-03-23 15:50 UTC by jusa

2020-03-23 16:06 UTC, mkosola approved these changes

2020-03-23 16:07 UTC, mlehtima requested changes
Wrong paths, ganges uses the led paths for virbator.

2020-03-23 16:10 UTC, mkosola commented
True, good catch

2020-03-24 07:55 UTC, mkosola approved these changes

2020-03-24 12:19 UTC, mlehtima approved these changes

2020-03-24 12:23 UTC, merged